### PR TITLE
HOLD: Support for guardduty exports

### PR DESCRIPTION
**Pull request by pjdufour-dds**
This PR includes support for GuardDuty logs.  I also added some comments to the source code on why the paths are what they are.  Now sure where you'd like those to be located.

### CODE REVIEW

**Comment by pjdufour-dds** [comment]
I'll try to get to this next week.

**Comment by pjdufour-dds** [comment]
Added a test.  Since GuardDuty exports still need to be manually configured, not sure if more is required for the test.  https://github.com/terraform-providers/terraform-provider-aws/issues/10920

**Comment by pjdufour-dds** [comment]
Rebased with master

**Comment by dynamike** [comment]
It looks like they added support for exports via terraform. Could you update your tests to use it? 

https://github.com/terraform-providers/terraform-provider-aws/pull/13894

**Comment by pjdufour-dds** [comment]
Holding for https://github.com/trussworks/terraform-aws-logs/pull/60

**Pull request closed without merging**
