### PR TITLE
Ee add aws provider v3 support to tf12 branch

### PR DESCRIPTION
**Pull request by eeeady**

### CODE REVIEW

**Comment by eeeady** [comment]
cc @mwarkentin 

I think one test might be broken... we'll find out soon. Hopefully this will get in sometime tomorrow.

**Comment by mwarkentin** [comment]
@eeeady amazing, appreciate the quick response!

**Comment by mwarkentin** [comment]
Looks like this was a little trickier than expected 🙈

**Comment by eeeady** [comment]
😢 Yeah... I was worried the tests would trip us up.

**Review by ralren — APPROVED** [review]

**Pull request merged**
